# Generated by Django 5.1.6 on 2025-03-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothinglibrary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("formal", "Formal Wear"),
                    ("casual", "Casual Wear"),
                    ("sports", "Sportswear"),
                    ("vintage", "Vintage"),
                    ("street", "Streetwear"),
                    ("active", "Activewear"),
                    ("denim", "Denim"),
                    ("outerwear", "Outerwear"),
                    ("accessories", "Accessories"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
