# Generated by Django 5.1.6 on 2025-04-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothinglibrary", "0005_borrowrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrequest",
            name="desired_duration",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
